language: cpp

os:
  - linux

dist: 
  - xenial
  
compiler:
  - gcc 
  
before_install:
  - sudo apt-get update
  - sudo apt-get install libpcsclite-dev
script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ..
  - make
  - cd ../WinscardTests/
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ..
  - make
  - ./WinscardTests
